version: '3.7'

services:
  api:
    build:
      context: ./api
    ports:
      - '5000:5000'
    environment:
      REDIS_URL: redis
    depends_on:
      - redis

  ai_worker:
    build:
      context: ./ai_worker
    environment:
      REDIS_URL: redis
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  redis-data:
